
//! Autogenerated weights for `pallet_reputation`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-07-27, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// ./target/release/node-template
// benchmark
// pallet
// --pallet
// pallet-reputation
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// ./pallets/substrate-palletes/reputation/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_example_basic.
pub trait WeightInfo {
	fn increase_reputation() -> Weight;
	fn decrease_reputation() -> Weight;
}

/// Weight functions for `pallet_reputation`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: Reputation Reputations (r:1 w:1)
	fn increase_reputation() -> Weight {
		(16_638_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Reputation Reputations (r:1 w:1)
	fn decrease_reputation() -> Weight {
		(15_930_000 as Weight)
			// Standard Error: 41_000
			// .saturating_add((29_000 as Weight).saturating_mul(s as Weight))
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}
